language: objective-c
matrix:
  include:
    - osx_image: xcode9.2
      env: 'SIMULATOR="name=iPad Pro (12.9-inch) (2nd generation),OS=11.2"'
    - osx_image: xcode8.3
      env: 'SIMULATOR="name=iPad Air 2,OS=10.3.1"'
    - osx_image: xcode7.3
      env: 'SIMULATOR="name=iPhone 6s,OS=9.3"'
    - osx_image: xcode6.4
      env: 'SIMULATOR="name=iPhone 4s,OS=8.4"'

before_install:
  - xcrun simctl list
  - brew update || brew update
  - rvm install 2.3.1
  - gem install bundler
install:
  - if [ -z "$(brew ls --versions coreutils)" ] ; then brew install coreutils ; fi
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - ./scripts/ci.sh "${SIMULATOR}"
